package io.siunertaq.mzv.smt

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}

// ─────────────────────────────────────────────────────────────────────────
//  PetersenSmtSolver
//
//  Invokes z3 (or another SMT-LIB 2 solver) on a suite generated by
//  PetersenSMTLib.  Parallel to YicesThresholdSolver in yices-bridge.
//
//  Usage:
//    PetersenSmtSolver.verify(PetersenSMTLib.renderSuite())
//
//  Environment:
//    Z3_PATH  — path to z3 binary (default: "z3")
// ─────────────────────────────────────────────────────────────────────────

enum MZVVerifyResult derives CanEqual:
  /** z3 returned unsat — property holds */
  case Unsat
  /** z3 returned sat — property holds (or counterexample found for negated form) */
  case Sat(model: String)
  /** z3 returned unknown or timed out */
  case Unknown(reason: String)

/** One parsed result block per echo+check-sat pair */
final case class PropertyResult(label: String, result: MZVVerifyResult)

object PetersenSmtSolver:

  private def z3Bin: String =
    sys.env.getOrElse("Z3_PATH", "z3")

  def isAvailable: Boolean =
    try
      ProcessBuilder(z3Bin, "--version").start().waitFor() == 0
    catch
      case _: Throwable => false

  /**
   * Verify a full SMT-LIB 2 suite.
   *
   * Returns Right(results) with one entry per check-sat call,
   * or Left(error) if z3 failed to run or produced unexpected output.
   *
   * Mirrors the API shape of YicesThresholdSolver.verify(problem).
   */
  def verify(smt2: String): Either[String, List[PropertyResult]] =
    run(smt2).map(parseResults)

  /**
   * Write suite to a .smt2 file (for inspection / manual replay).
   * Mirrors the artifact-writing pattern in YicesThresholdSmokeSpec.
   */
  def writeArtifact(path: Path, smt2: String): Unit =
    Files.createDirectories(path.getParent)
    Files.writeString(path, smt2, StandardCharsets.UTF_8)

  // ── Internal ──────────────────────────────────────────────────────────

  private def run(smt2: String): Either[String, String] =
    try
      val proc = ProcessBuilder(z3Bin, "-in").start()
      proc.getOutputStream.write(smt2.getBytes(StandardCharsets.UTF_8))
      proc.getOutputStream.close()
      val stdout  = scala.io.Source.fromInputStream(proc.getInputStream).mkString
      val stderr  = scala.io.Source.fromInputStream(proc.getErrorStream).mkString
      val exitCode = proc.waitFor()
      if exitCode == 0 then Right(stdout)
      else Left(s"z3 exited $exitCode: ${stderr.trim}")
    catch
      case t: Throwable => Left(s"Failed to start z3: ${t.getMessage}")

  /**
   * Parse interleaved echo + check-sat output.
   *
   * z3 echoes each `(echo "label")` and follows each `(check-sat)` with
   * sat/unsat/unknown, and each `(get-value ...)` with a model expression.
   * We reconstruct the pairing by consuming lines in order.
   */
  private def parseResults(output: String): List[PropertyResult] =
    val lines  = output.linesIterator.map(_.trim).toList
    val bldr   = List.newBuilder[PropertyResult]
    var buf    = lines

    while buf.nonEmpty do
      buf.head match
        case label if label.startsWith("P") && label.endsWith("]") =>
          // Echo label (e.g. "P1: diameter<=2 ... [expect unsat]")
          buf = buf.tail
          buf match
            case "unsat" :: rest =>
              bldr += PropertyResult(label, MZVVerifyResult.Unsat)
              buf = rest
            case "sat" :: rest =>
              // Collect optional model lines until the next label or EOF
              val (modelLines, remaining) = rest.span(l =>
                !l.startsWith("P") && l.nonEmpty)
              bldr += PropertyResult(label, MZVVerifyResult.Sat(modelLines.mkString("\n")))
              buf = remaining
            case "unknown" :: rest =>
              bldr += PropertyResult(label, MZVVerifyResult.Unknown("z3 returned unknown"))
              buf = rest
            case _ =>
              buf = buf.tail   // skip unexpected
        case _ =>
          buf = buf.tail       // skip preamble / blank lines

    bldr.result()

  /** Quick summary for logging — mirrors YicesThresholdSolver style */
  def summarize(results: List[PropertyResult]): String =
    results.map {
      case PropertyResult(lbl, MZVVerifyResult.Unsat)        => s"✓ UNSAT  $lbl"
      case PropertyResult(lbl, MZVVerifyResult.Sat(model))   => s"✓ SAT    $lbl\n  $model"
      case PropertyResult(lbl, MZVVerifyResult.Unknown(why)) => s"? UNKNWN $lbl ($why)"
    }.mkString("\n")
